apiVersion: v1
kind: ConfigMap
metadata:
  name: stackfood-products-config
  labels:
    app.kubernetes.io/name: stackfood-products
    app.kubernetes.io/part-of: stackfood
data:
  # Database Configuration
  ConnectionStrings__DefaultConnection: "Host=stackfood-db.c7u6s4akq7qg.us-east-1.rds.amazonaws.com;Port=5432;Database=stackfood_products;Username=stackfood;Password=postgres"

  # Application Settings
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
