apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: products

bases:
  - ../base

resources:
  - configmap.yaml
  - secret.yaml

images:
  - name: ghcr.io/stack-food/stackfood-product-api
    newTag: main

replicas:
  - name: stackfood-products
    count: 2
