apiVersion: v1
kind: Secret
metadata:
  name: stackfood-products-secrets
  labels:
    app.kubernetes.io/name: stackfood-products
    app.kubernetes.io/part-of: stackfood
type: Opaque
stringData:
  # Database Password
  POSTGRES_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
