apiVersion: v1
kind: Service
metadata:
  name: stackfood-products
  labels:
    app.kubernetes.io/name: stackfood-products
    app.kubernetes.io/instance: stackfood-products
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: stackfood
    app: stackfood-products
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: stackfood-products
    app: stackfood-products
